DROP TABLE IF EXISTS `chapitres`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `chapitres` (
  `code_chapitre` int(5) NOT NULL DEFAULT 0,
  `description_chapitre` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`code_chapitre`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `chapitres`
--

LOCK TABLES `chapitres` WRITE;
/*!40000 ALTER TABLE `chapitres` DISABLE KEYS */;
INSERT INTO `chapitres` VALUES
(100,'Logique, ensemble, raisonnement'),
(101,'Injection, surjection, bijection'),
(102,'Dénombrement'),
(103,'Arithmétique dans Z'),
(104,'Nombres complexes'),
(105,'Polynôme, fraction rationnelle'),
(106,'Espace vectoriel'),
(107,'Application linéaire'),
(108,'Matrice'),
(120,'Propriétés de R'),
(121,'Suite'),
(122,'Série numérique'),
(123,'Continuité, limite et étude de fonctions réelles'),
(124,'Dérivabilité des fonctions réelles'),
(125,'Développement limité'),
(126,'Fonctions circulaires et hyperboliques inverses'),
(127,'Calcul d\'intégrales'),
(200,'Déterminant, système linéaire'),
(201,'Réduction d\'endomorphisme, polynôme annulateur'),
(202,'Endomorphisme particulier'),
(203,'Groupe, anneau, corps'),
(204,'Espace euclidien, espace normé'),
(205,'Arithmétique'),
(220,'Série entière'),
(221,'Série de Fourier'),
(222,'Suite et série de fonctions'),
(223,'Fonction de plusieurs variables'),
(224,'Intégration'),
(225,'Equation différentielle'),
(140,'Géométrie du plan'),
(229,'Topologie'),
(240,'Géométrie affine dans le plan et dans l\'espace'),
(241,'Isométrie vectorielle'),
(242,'Géométrie affine euclidienne'),
(243,'Conique'),
(244,'Courbes planes'),
(141,'Géométrie de l\'espace'),
(245,'Analyse vectorielle'),
(246,'Surfaces'),
(260,'Probabilité discrète'),
(261,'Probabilité continue'),
(262,'Statistique'),
(300,'Groupe quotient, théorème de Lagrange'),
(301,'Ordre d\'un élément'),
(302,'Groupe symétrique, décomposition en cycles disjoints, signature'),
(303,'Sous-groupe distingué'),
(304,'Action de groupe'),
(305,'Groupe cyclique'),
(306,'Théorème de Sylow'),
(307,'Autre'),
(310,'Isométrie euclidienne'),
(311,'Géométrie différentielle élémentaire de R^n'),
(312,'Géométrie et trigonométrie sphérique'),
(313,'Groupe orthogonal et quaternions'),
(314,'Géométrie projective'),
(315,'Géométrie et trigonométrie hyperbolique'),
(316,'Autre'),
(320,'Groupe'),
(321,'Sous-groupe, morphisme'),
(322,'Groupe fini'),
(323,'Anneau, corps'),
(324,'Polynôme'),
(325,'Extension de corps'),
(326,'Extension d\'anneau'),
(327,'Autre'),
(350,'Variété'),
(351,'Immersion, submersion, plongement'),
(352,'Sous-variété'),
(353,'Espace tangent, application linéaire tangente'),
(354,'Champ de vecteurs'),
(355,'Forme différentielle'),
(356,'Orientation'),
(357,'Intégration sur les variétés'),
(358,'Autre'),
(370,'Différentiabilité, calcul de différentielles'),
(371,'Différentielle d\'ordre supérieur, formule de Taylor'),
(372,'Difféomorphisme, théorème d\'inversion locale et des fonctions implicites'),
(373,'Extremum, extremum lié'),
(374,'Autre'),
(380,'Solution maximale'),
(381,'Théorème de Cauchy-Lipschitz'),
(382,'Système linéaire à  coefficients constants'),
(383,'Etude qualititative : équilibre, stabilité'),
(384,'Equation aux dérivées partielles'),
(385,'Autre'),
(400,'Tribu, fonction mesurable'),
(401,'Mesure'),
(402,'Lemme de Fatou, convergence monotone'),
(403,'Théorème de convergence dominée'),
(404,'Intégrales multiples, théorème de Fubini'),
(405,'Intégrale dépendant d\'un paramètre'),
(406,'Espace L^p'),
(407,'Transformée de Fourier'),
(408,'Autre'),
(420,'Espace topologique, espace métrique'),
(421,'Compacité'),
(422,'Continuité, uniforme continuité'),
(423,'Application linéaire bornée'),
(424,'Espace vectoriel normé'),
(425,'Espace métrique complet, espace de Banach'),
(426,'Théorème du point fixe'),
(427,'Espace de Hilbert, théorème de projection'),
(428,'Théorème de Baire'),
(429,'Dualité, topologie faible'),
(430,'Connexité'),
(440,'Fonction holomorphe'),
(441,'Fonction logarithme et fonction puissance'),
(442,'Formule de Cauchy'),
(443,'Singularité'),
(444,'Théorème des résidus'),
(445,'Tranformée de Laplace et de Fourier'),
(446,'Autre'),
(450,'Interpolation polynomiale'),
(451,'Courbe de Bézier, spline'),
(452,'Intégration numérique'),
(453,'Méthode de Newton'),
(454,'Résolution d\'équation différentielle'),
(455,'Résolution de systèmes linéaires : méthode directe'),
(456,'Résolution de systèmes linéaires : méthode itérative'),
(457,'Résolution de systèmes linéaires : méthode de gradient'),
(458,'Calcul de valeurs propres et de vecteurs propres'),
(459,'Autre'),
(470,'Fonction convexe'),
(471,'Multiplicateurs de Lagrange'),
(472,'Algorithme d\'Uzawa'),
(473,'Algorithme du simplexe'),
(474,'Autre'),
(480,'Loi, indépendance, loi conditionnelle'),
(481,'Variance, covariance, fonction génératrice'),
(482,'Convergence de variables aléatoires'),
(483,'Lois des grands nombres, théorème central limite'),
(484,'Estimateur'),
(485,'Tests sur la moyenne, test du chi2'),
(486,'Chaînes de Markov'),
(487,'Autre'),
(431,'Autre'),
(432,'Théorème de Stone-Weirstrass, théorème d\'Ascoli'),
(328,'Forme bilinéaire');